### ISSUE TITLE
Editable Draft MVP

### ISSUE THREAD

**Issue by knowtheory** [BadIdeaFactory/demand-editable-drafts#1]
# Phase 1: Technology proving ground

Our initial milestone is proving out that layout data can be extracted in browser via some combination of `pdf.js` and tesseract.js.

- [x] [Load `pdf.js` with a Svelte app & render a test PDF](https://github.com/BadIdeaFactory/demand-editable-drafts/issues/2)
- [x] [Extract text & layout from PDF](https://github.com/BadIdeaFactory/demand-editable-drafts/issues/3) (with `pdf.js` or with `tesseract.js`)

# Phase 2: Main Functionality

- [x] [loading PDFs from the user](https://github.com/BadIdeaFactory/demand-editable-drafts/issues/4) (and perhaps by URL?)
- [x] Layout analysis to find main content
- [x] font style identification?
- [ ] Site layout designs
- [x] [Decisions about output formats](https://github.com/BadIdeaFactory/demand-editable-drafts/issues/5)

# Phase 3: App & Deployment

- [ ] Analytics configuration
- [ ] Stress testing & performance improvement
- [ ] Site Copy
- [ ] ad hoc user testing & further refinements.
